<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '\'{class}\' must extend from \'yii\\rbac\\Rule\' or its child class' => '',
    'Action' => '',
    'Are you sure to delete this item?' => '',
    'Assign' => '',
    'Assignment : {0}' => '',
    'Assignments' => '',
    'Class Name' => '',
    'Create' => '',
    'Create ' => '',
    'Create Rule' => '',
    'Data' => '',
    'Delete' => '',
    'Description' => '',
    'Invalid rule "{value}"' => '',
    'Item has been removed.' => '',
    'Item has been saved.' => '',
    'Name' => '',
    'Permissions' => '',
    'Refresh' => '',
    'Remove' => '',
    'Roles' => '',
    'Routes' => '',
    'Rule' => '',
    'Rule "{value}" does not exists' => '',
    'Rule : {0}' => '',
    'Rule Name' => '',
    'Rule has been deleted.' => '',
    'Rule has been saved.' => '',
    'Rules' => '',
    'Search for assigned' => '',
    'Search for available' => '',
    'Select Rule' => '',
    'The requested page does not exist.' => '',
    'Type' => '',
    'Unknown class \'{class}\'' => '',
    'Update' => '',
    'Update ' => '',
    'Update Rule : {0}' => '',
];
