<?php

namespace app\models;

use app\behaviors\LogBehavior;
use app\delivery\DeliveryHelper;
use app\models\queries\DeliveryStatusQuery;
use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "{{%delivery_status}}".
 *
 * @property int $id
 * @property int $order_id
 * @property string $status
 * @property string $status_key
 * @property string $status_date
 * @property string $description
 * @property int $created_at
 *
 * @property Order $order
 */
class DeliveryStatus extends ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%delivery_status}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['order_id', 'status'], 'required'],
            [['created_at'], 'default', 'value' => time()],
            [['order_id', 'created_at', 'status_date'], 'integer'],
            [['status', 'status_key', 'description'], 'string'],
            [['order_id'], 'exist', 'skipOnError' => true, 'targetClass' => Order::className(), 'targetAttribute' => ['order_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'order_id' => Yii::t('app', 'Order ID'),
            'status' => Yii::t('app', 'Status'),
            'status_key' => Yii::t('app', 'Status key'),
            'status_date' => Yii::t('app', 'Status date'),
            'created_at' => Yii::t('app', 'Created At'),
            'description' => Yii::t('app', 'Description'),
        ];
    }

    public function fields()
    {
        $fields = parent::fields();

        $fields['created_at'] = function () {
            return date('d.m.Y \в H:i', $this->created_at);
        };

        $fields['fastery_status'] = function () {
            return (new Order())->getWorkflowStatusName($this->order->status);
        };

        $fields['shop_order_number'] = function () {
            return $this->order->shop_order_number;
        };

        $fields['carrier_key'] = function () {
            return DeliveryHelper::getName($this->order->delivery->carrier_key);
        };

        $fields['address'] = function () {
            return $this->order->address->full_address;
        };

        return $fields;
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOrder()
    {
        return $this->hasOne(Order::className(), ['id' => 'order_id']);
    }

    /**
     * @inheritdoc
     * @return DeliveryStatusQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new DeliveryStatusQuery(get_called_class());
    }

    public function afterFind()
    {
        parent::afterFind(); // TODO: Change the autogenerated stub
        $this->status_date = date('d.m.Y \в H:i', (int) $this->status_date + (3 * 3600));
    }
}
